// 现代化宝宝起名字库 - 精选时尚好听汉字，告别老气，拥抱现代美学

const NAME_DATABASE = [
    // ===== 金属性字符 - 现代时尚 =====
    { char: '睿', element: '金', meaning: '睿智深远，聪明睿智', strokes: 14, gender: ['both'], pinyin: 'ruì', style: 'modern' },
    { char: '钰', element: '金', meaning: '珍宝美玉，贵重珍贵', strokes: 13, gender: ['both'], pinyin: 'yù', style: 'elegant' },
    { char: '锐', element: '金', meaning: '锐意进取，才思敏锐', strokes: 15, gender: ['male'], pinyin: 'ruì', style: 'modern' },
    { char: '锦', element: '金', meaning: '前程似锦，美好未来', strokes: 16, gender: ['both'], pinyin: 'jǐn', style: 'elegant' },
    { char: '诚', element: '金', meaning: '诚实守信，真诚待人', strokes: 14, gender: ['both'], pinyin: 'chéng', style: 'classic' },
    { char: '承', element: '金', meaning: '承继传统，承担责任', strokes: 8, gender: ['both'], pinyin: 'chéng', style: 'modern' },
    { char: '宸', element: '金', meaning: '帝王宫殿，尊贵高雅', strokes: 10, gender: ['both'], pinyin: 'chén', style: 'elegant' },
    { char: '晨', element: '金', meaning: '晨光熹微，朝气蓬勃', strokes: 11, gender: ['both'], pinyin: 'chén', style: 'fresh' },
    { char: '思', element: '金', meaning: '思维敏捷，深思熟虑', strokes: 9, gender: ['both'], pinyin: 'sī', style: 'elegant' },
    { char: '新', element: '金', meaning: '新颖独特，推陈出新', strokes: 13, gender: ['both'], pinyin: 'xīn', style: 'modern' },
    { char: '心', element: '金', meaning: '善良纯真，用心良苦', strokes: 4, gender: ['both'], pinyin: 'xīn', style: 'simple' },
    { char: '悦', element: '金', meaning: '心悦诚服，愉悦快乐', strokes: 11, gender: ['both'], pinyin: 'yuè', style: 'joyful' },
    { char: '喜', element: '金', meaning: '喜气洋洋，喜从天降', strokes: 12, gender: ['both'], pinyin: 'xǐ', style: 'joyful' },
    { char: '诗', element: '金', meaning: '诗情画意，文采斐然', strokes: 13, gender: ['both'], pinyin: 'shī', style: 'literary' },
    { char: '星', element: '金', meaning: '星光闪耀，前途光明', strokes: 9, gender: ['both'], pinyin: 'xīng', style: 'dreamy' },
    { char: '紫', element: '金', meaning: '紫气东来，高贵典雅', strokes: 12, gender: ['female'], pinyin: 'zǐ', style: 'elegant' },
    { char: '钧', element: '金', meaning: '重量千钧，稳重可靠', strokes: 12, gender: ['male'], pinyin: 'jūn', style: 'strong' },
    { char: '静', element: '金', meaning: '安静恬淡，心如止水', strokes: 16, gender: ['female'], pinyin: 'jìng', style: 'peaceful' },
    { char: '初', element: '金', meaning: '初心不改，纯真美好', strokes: 7, gender: ['both'], pinyin: 'chū', style: 'pure' },
    { char: '秋', element: '金', meaning: '秋高气爽，收获满满', strokes: 9, gender: ['both'], pinyin: 'qiū', style: 'fruitful' },

    // ===== 木属性字符 - 自然清新 =====
    { char: '梓', element: '木', meaning: '梓材良木，成才之材', strokes: 11, gender: ['both'], pinyin: 'zǐ', style: 'modern' },
    { char: '楠', element: '木', meaning: '楠木珍贵，品质优良', strokes: 13, gender: ['both'], pinyin: 'nán', style: 'elegant' },
    { char: '杰', element: '木', meaning: '杰出人才，超群出众', strokes: 12, gender: ['male'], pinyin: 'jié', style: 'classic' },
    { char: '梦', element: '木', meaning: '梦想成真，理想远大', strokes: 14, gender: ['both'], pinyin: 'mèng', style: 'dreamy' },
    { char: '枫', element: '木', meaning: '枫叶如丹，美丽动人', strokes: 13, gender: ['both'], pinyin: 'fēng', style: 'natural' },
    { char: '颖', element: '木', meaning: '聪颖过人，才思敏捷', strokes: 16, gender: ['female'], pinyin: 'yǐng', style: 'smart' },
    { char: '雅', element: '木', meaning: '高雅脱俗，品味不凡', strokes: 12, gender: ['female'], pinyin: 'yǎ', style: 'elegant' },
    { char: '彦', element: '木', meaning: '才德兼备，德才并茂', strokes: 9, gender: ['male'], pinyin: 'yàn', style: 'scholarly' },
    { char: '琪', element: '木', meaning: '美玉珍贵，琪花瑶草', strokes: 13, gender: ['female'], pinyin: 'qí', style: 'precious' },
    { char: '琳', element: '木', meaning: '琳琅满目，美玉如琳', strokes: 13, gender: ['female'], pinyin: 'lín', style: 'precious' },
    { char: '兰', element: '木', meaning: '兰花幽香，品质高雅', strokes: 9, gender: ['female'], pinyin: 'lán', style: 'elegant' },
    { char: '萱', element: '木', meaning: '萱草忘忧，快乐无忧', strokes: 15, gender: ['female'], pinyin: 'xuān', style: 'joyful' },
    { char: '可', element: '木', meaning: '可爱动人，令人喜爱', strokes: 5, gender: ['both'], pinyin: 'kě', style: 'cute' },
    { char: '君', element: '木', meaning: '君子之风，品格高尚', strokes: 7, gender: ['both'], pinyin: 'jūn', style: 'noble' },
    { char: '凯', element: '木', meaning: '凯旋而归，胜利在望', strokes: 12, gender: ['male'], pinyin: 'kǎi', style: 'victorious' },
    { char: '茜', element: '木', meaning: '茜草红艳，美丽动人', strokes: 12, gender: ['female'], pinyin: 'qiàn', style: 'beautiful' },
    { char: '芊', element: '木', meaning: '草木茂盛，生机勃勃', strokes: 9, gender: ['female'], pinyin: 'qiān', style: 'fresh' },
    { char: '苏', element: '木', meaning: '苏醒复活，生机盎然', strokes: 7, gender: ['both'], pinyin: 'sū', style: 'fresh' },
    { char: '若', element: '木', meaning: '若如所愿，美好如意', strokes: 11, gender: ['both'], pinyin: 'ruò', style: 'gentle' },
    { char: '柔', element: '木', meaning: '温柔贤淑，柔情似水', strokes: 9, gender: ['female'], pinyin: 'róu', style: 'gentle' },
    { char: '果', element: '木', meaning: '果实累累，成果丰硕', strokes: 8, gender: ['both'], pinyin: 'guǒ', style: 'fruitful' },
    { char: '朵', element: '木', meaning: '花朵绽放，美丽可爱', strokes: 6, gender: ['female'], pinyin: 'duǒ', style: 'lovely' },
    { char: '艾', element: '木', meaning: '艾草清香，纯洁美好', strokes: 8, gender: ['both'], pinyin: 'ài', style: 'pure' },
    { char: '语', element: '木', meaning: '语言优美，才思敏捷', strokes: 14, gender: ['both'], pinyin: 'yǔ', style: 'eloquent' },

    // ===== 水属性字符 - 灵动智慧 =====
    { char: '涵', element: '水', meaning: '包容涵养，修养深厚', strokes: 12, gender: ['both'], pinyin: 'hán', style: 'cultivated' },
    { char: '泽', element: '水', meaning: '恩泽深厚，福泽绵长', strokes: 17, gender: ['both'], pinyin: 'zé', style: 'benevolent' },
    { char: '清', element: '水', meaning: '清正廉明，品格高洁', strokes: 12, gender: ['both'], pinyin: 'qīng', style: 'pure' },
    { char: '浩', element: '水', meaning: '浩然正气，气势如虹', strokes: 11, gender: ['male'], pinyin: 'hào', style: 'magnificent' },
    { char: '博', element: '水', meaning: '博学多才，博古通今', strokes: 12, gender: ['both'], pinyin: 'bó', style: 'learned' },
    { char: '文', element: '水', meaning: '文质彬彬，文采飞扬', strokes: 4, gender: ['both'], pinyin: 'wén', style: 'literary' },
    { char: '慧', element: '水', meaning: '聪慧过人，智慧如海', strokes: 15, gender: ['female'], pinyin: 'huì', style: 'wise' },
    { char: '惠', element: '水', meaning: '惠泽他人，仁慈善良', strokes: 12, gender: ['female'], pinyin: 'huì', style: 'kind' },
    { char: '美', element: '水', meaning: '美丽动人，美好如画', strokes: 9, gender: ['female'], pinyin: 'měi', style: 'beautiful' },
    { char: '妍', element: '水', meaning: '妍丽动人，美好可爱', strokes: 7, gender: ['female'], pinyin: 'yán', style: 'beautiful' },
    { char: '雨', element: '水', meaning: '甘露时雨，滋润万物', strokes: 8, gender: ['both'], pinyin: 'yǔ', style: 'natural' },
    { char: '雪', element: '水', meaning: '雪花纯洁，冰清玉洁', strokes: 11, gender: ['female'], pinyin: 'xuě', style: 'pure' },
    { char: '霖', element: '水', meaning: '甘霖普降，福泽深厚', strokes: 16, gender: ['both'], pinyin: 'lín', style: 'blessing' },
    { char: '溪', element: '水', meaning: '溪水潺潺，清雅动人', strokes: 14, gender: ['both'], pinyin: 'xī', style: 'gentle' },
    { char: '汐', element: '水', meaning: '汐水轻柔，温柔如水', strokes: 7, gender: ['female'], pinyin: 'xī', style: 'gentle' },
    { char: '沐', element: '水', meaning: '沐浴阳光，受到恩泽', strokes: 8, gender: ['both'], pinyin: 'mù', style: 'blessed' },
    { char: '洁', element: '水', meaning: '洁白无瑕，纯洁美好', strokes: 16, gender: ['female'], pinyin: 'jié', style: 'pure' },
    { char: '澜', element: '水', meaning: '波澜壮阔，气势宏大', strokes: 21, gender: ['both'], pinyin: 'lán', style: 'magnificent' },
    { char: '潇', element: '水', meaning: '潇洒自如，风度翩翩', strokes: 20, gender: ['both'], pinyin: 'xiāo', style: 'elegant' },
    { char: '冬', element: '水', meaning: '冬雪纯洁，宁静致远', strokes: 5, gender: ['both'], pinyin: 'dōng', style: 'serene' },
    { char: '欢', element: '水', meaning: '欢声笑语，欢乐祥和', strokes: 22, gender: ['both'], pinyin: 'huān', style: 'joyful' },

    // ===== 火属性字符 - 阳光活力 =====
    { char: '煜', element: '火', meaning: '光彩照人，熠熠生辉', strokes: 13, gender: ['both'], pinyin: 'yù', style: 'brilliant' },
    { char: '烨', element: '火', meaning: '烨烨生辉，光芒万丈', strokes: 16, gender: ['both'], pinyin: 'yè', style: 'brilliant' },
    { char: '灿', element: '火', meaning: '灿烂辉煌，光彩夺目', strokes: 17, gender: ['both'], pinyin: 'càn', style: 'brilliant' },
    { char: '晖', element: '火', meaning: '阳光普照，温暖如春', strokes: 13, gender: ['both'], pinyin: 'huī', style: 'warm' },
    { char: '明', element: '火', meaning: '明察秋毫，聪明睿智', strokes: 8, gender: ['both'], pinyin: 'míng', style: 'bright' },
    { char: '丹', element: '火', meaning: '丹心赤诚，纯真无邪', strokes: 4, gender: ['female'], pinyin: 'dān', style: 'sincere' },
    { char: '丽', element: '火', meaning: '美丽大方，丽质天成', strokes: 19, gender: ['female'], pinyin: 'lì', style: 'beautiful' },
    { char: '娜', element: '火', meaning: '婀娜多姿，娜娜动人', strokes: 10, gender: ['female'], pinyin: 'nà', style: 'graceful' },
    { char: '婷', element: '火', meaning: '婷婷袅袅，美丽动人', strokes: 12, gender: ['female'], pinyin: 'tíng', style: 'graceful' },
    { char: '媛', element: '火', meaning: '淑女贤媛，品德优良', strokes: 12, gender: ['female'], pinyin: 'yuàn', style: 'virtuous' },
    { char: '乐', element: '火', meaning: '快乐无忧，乐观向上', strokes: 15, gender: ['both'], pinyin: 'lè', style: 'joyful' },
    { char: '俊', element: '火', meaning: '俊朗英俊，人才俊秀', strokes: 9, gender: ['male'], pinyin: 'jùn', style: 'handsome' },
    { char: '亮', element: '火', meaning: '聪明亮丽，光明磊落', strokes: 9, gender: ['both'], pinyin: 'liàng', style: 'bright' },
    { char: '晴', element: '火', meaning: '晴空万里，心情开朗', strokes: 12, gender: ['female'], pinyin: 'qíng', style: 'sunny' },
    { char: '朗', element: '火', meaning: '朗朗乾坤，开朗豁达', strokes: 11, gender: ['male'], pinyin: 'lǎng', style: 'cheerful' },
    { char: '昊', element: '火', meaning: '昊天罔极，胸怀广阔', strokes: 8, gender: ['male'], pinyin: 'hào', style: 'vast' },
    { char: '瑶', element: '火', meaning: '瑶池仙境，美玉如瑶', strokes: 15, gender: ['female'], pinyin: 'yáo', style: 'precious' },
    { char: '琰', element: '火', meaning: '美玉无瑕，品德高尚', strokes: 13, gender: ['female'], pinyin: 'yǎn', style: 'precious' },
    { char: '曦', element: '火', meaning: '晨曦微露，希望之光', strokes: 20, gender: ['both'], pinyin: 'xī', style: 'hopeful' },
    { char: '暖', element: '火', meaning: '温暖如春，关怀备至', strokes: 13, gender: ['both'], pinyin: 'nuǎn', style: 'warm' },
    { char: '夏', element: '火', meaning: '夏日阳光，热情活力', strokes: 10, gender: ['both'], pinyin: 'xià', style: 'energetic' },
    { char: '日', element: '火', meaning: '日光普照，光明正大', strokes: 4, gender: ['both'], pinyin: 'rì', style: 'bright' },
    { char: '爱', element: '火', meaning: '爱心满满，温暖如春', strokes: 13, gender: ['both'], pinyin: 'ài', style: 'loving' },
    { char: '宁', element: '火', meaning: '宁静致远，心如止水', strokes: 14, gender: ['both'], pinyin: 'níng', style: 'peaceful' },
    { char: '暄', element: '火', meaning: '暄和温暖，春意盎然', strokes: 13, gender: ['both'], pinyin: 'xuān', style: 'warm' },
    { char: '易', element: '火', meaning: '易如反掌，聪明伶俐', strokes: 8, gender: ['both'], pinyin: 'yì', style: 'clever' },

    // ===== 土属性字符 - 稳重大气 =====
    { char: '宇', element: '土', meaning: '宇宙广阔，胸襟开阔', strokes: 6, gender: ['male'], pinyin: 'yǔ', style: 'vast' },
    { char: '辰', element: '土', meaning: '星辰大海，志向远大', strokes: 7, gender: ['both'], pinyin: 'chén', style: 'stellar' },
    { char: '轩', element: '土', meaning: '气宇轩昂，风度翩翩', strokes: 10, gender: ['male'], pinyin: 'xuān', style: 'noble' },
    { char: '坤', element: '土', meaning: '大地载物，厚德载物', strokes: 8, gender: ['male'], pinyin: 'kūn', style: 'virtuous' },
    { char: '城', element: '土', meaning: '城池坚固，稳如磐石', strokes: 10, gender: ['both'], pinyin: 'chéng', style: 'stable' },
    { char: '培', element: '土', meaning: '培育成才，栽培英才', strokes: 11, gender: ['both'], pinyin: 'péi', style: 'nurturing' },
    { char: '安', element: '土', meaning: '安居乐业，平安幸福', strokes: 6, gender: ['both'], pinyin: 'ān', style: 'peaceful' },
    { char: '远', element: '土', meaning: '远大前程，志向远大', strokes: 17, gender: ['both'], pinyin: 'yuǎn', style: 'ambitious' },
    { char: '越', element: '土', meaning: '越来越好，超越自我', strokes: 12, gender: ['both'], pinyin: 'yuè', style: 'progressive' },
    { char: '优', element: '土', meaning: '优秀卓越，品学兼优', strokes: 17, gender: ['both'], pinyin: 'yōu', style: 'excellent' },
    { char: '阳', element: '土', meaning: '阳光灿烂，朝气蓬勃', strokes: 17, gender: ['both'], pinyin: 'yáng', style: 'sunny' },
    { char: '勇', element: '土', meaning: '勇敢无畏，英勇善战', strokes: 9, gender: ['male'], pinyin: 'yǒng', style: 'brave' },
    { char: '威', element: '土', meaning: '威风凛凛，威武不屈', strokes: 9, gender: ['male'], pinyin: 'wēi', style: 'mighty' },
    { char: '峰', element: '土', meaning: '登峰造极，山峰险峻', strokes: 10, gender: ['male'], pinyin: 'fēng', style: 'ambitious' },
    { char: '韵', element: '土', meaning: '韵味十足，风韵优雅', strokes: 19, gender: ['female'], pinyin: 'yùn', style: 'elegant' },
    { char: '怡', element: '土', meaning: '怡然自得，心情愉悦', strokes: 9, gender: ['female'], pinyin: 'yí', style: 'pleasant' },
    { char: '嫣', element: '土', meaning: '嫣然一笑，美丽动人', strokes: 14, gender: ['female'], pinyin: 'yān', style: 'charming' },
    { char: '婉', element: '土', meaning: '婉约温柔，温文尔雅', strokes: 11, gender: ['female'], pinyin: 'wǎn', style: 'gentle' },
    { char: '亦', element: '土', meaning: '亦可亦美，多才多艺', strokes: 6, gender: ['both'], pinyin: 'yì', style: 'versatile' },
    { char: '以', element: '土', meaning: '以德服人，品德高尚', strokes: 5, gender: ['both'], pinyin: 'yǐ', style: 'virtuous' },
    { char: '月', element: '土', meaning: '月色如水，温柔美好', strokes: 4, gender: ['female'], pinyin: 'yuè', style: 'gentle' },
    { char: '一', element: '土', meaning: '一心一意，专一执着', strokes: 1, gender: ['both'], pinyin: 'yī', style: 'simple' },
    { char: '依', element: '土', meaning: '依恋温暖，温柔可人', strokes: 8, gender: ['female'], pinyin: 'yī', style: 'tender' },
    { char: '伊', element: '土', meaning: '伊人如梦，美好如画', strokes: 6, gender: ['female'], pinyin: 'yī', style: 'dreamy' },
    { char: '予', element: '土', meaning: '予人玫瑰，手有余香', strokes: 4, gender: ['both'], pinyin: 'yǔ', style: 'giving' },
    { char: '羽', element: '土', meaning: '羽翼丰满，自由翱翔', strokes: 6, gender: ['both'], pinyin: 'yǔ', style: 'free' },
    { char: '逸', element: '土', meaning: '逸群之才，卓越超群', strokes: 15, gender: ['both'], pinyin: 'yì', style: 'outstanding' }
];

// 现代流行姓名组合（避免老气）
const MODERN_COMBINATIONS = {
    male: [
        ['宇', '轩'], ['浩', '然'], ['子', '轩'], ['梓', '轩'], ['子', '涵'], ['梓', '涵'],
        ['俊', '熙'], ['俊', '宇'], ['梓', '豪'], ['子', '豪'], ['浩', '宇'], ['煜', '祺'],
        ['辰', '轩'], ['辰', '宇'], ['博', '文'], ['博', '涵'], ['子', '墨'], ['梓', '墨'],
        ['睿', '泽'], ['睿', '轩'], ['明', '轩'], ['明', '泽'], ['子', '昂'], ['梓', '昂'],
        ['凯', '然'], ['凯', '轩'], ['君', '浩'], ['君', '泽'], ['彦', '博'], ['彦', '泽']
    ],
    female: [
        ['雨', '桐'], ['语', '桐'], ['诗', '涵'], ['诗', '雅'], ['梓', '涵'], ['子', '涵'],
        ['语', '汐'], ['诗', '汐'], ['若', '汐'], ['苏', '汐'], ['沐', '晴'], ['沐', '阳'],
        ['艾', '琳'], ['艾', '嘉'], ['欣', '妍'], ['欣', '悦'], ['语', '嫣'], ['诗', '嫣'],
        ['梓', '萱'], ['子', '萱'], ['雨', '萱'], ['语', '萱'], ['若', '伊'], ['苏', '伊'],
        ['思', '雅'], ['思', '涵'], ['美', '琳'], ['美', '嘉'], ['静', '雅'], ['静', '怡']
    ]
};

// 风格分类
const NAME_STYLES = {
    modern: ['时尚现代', '符合当代审美'],
    elegant: ['优雅高贵', '气质出众'],
    fresh: ['清新自然', '朝气蓬勃'],
    gentle: ['温柔如水', '柔情似水'],
    brilliant: ['光彩夺目', '才华横溢'],
    literary: ['文艺气息', '书香门第'],
    cute: ['可爱活泼', '童真可爱'],
    noble: ['高贵典雅', '气度不凡'],
    joyful: ['欢乐喜悦', '开朗活泼'],
    dreamy: ['梦幻浪漫', '充满想象'],
    peaceful: ['宁静致远', '心境平和'],
    pure: ['纯洁美好', '清新脱俗']
};

// 导出字库数据
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { NAME_DATABASE, MODERN_COMBINATIONS, NAME_STYLES };
} 