// 宝宝起名字库数据库 - 包含精选汉字，涵盖五行、笔画、寓意、适用性别、拼音等信息

const NAME_DATABASE = [
    // ===== 金属性字符 =====
    { char: '鑫', element: '金', meaning: '财富兴盛，三金聚财', strokes: 24, gender: ['male', 'both'] },
    { char: '钰', element: '金', meaning: '珍宝美玉，贵重珍贵', strokes: 13, gender: ['both'], pinyin: 'yù' },
    { char: '铭', element: '金', meaning: '铭记在心，永不忘怀', strokes: 14, gender: ['male'], pinyin: 'míng' },
    { char: '锐', element: '金', meaning: '锐意进取，才思敏锐', strokes: 15, gender: ['male'], pinyin: 'ruì' },
    { char: '钢', element: '金', meaning: '坚强刚毅，意志如钢', strokes: 16, gender: ['male'] },
    { char: '银', element: '金', meaning: '珍贵纯洁，如银般闪耀', strokes: 14, gender: ['both'] },
    { char: '锦', element: '金', meaning: '前程似锦，美好未来', strokes: 16, gender: ['both'] },
    { char: '睿', element: '金', meaning: '睿智深远，聪明睿智', strokes: 14, gender: ['both'], pinyin: 'ruì' },
    { char: '诚', element: '金', meaning: '诚实守信，真诚待人', strokes: 14, gender: ['both'], pinyin: 'chéng' },
    { char: '成', element: '金', meaning: '功成名就，事业有成', strokes: 7, gender: ['both'] },
    { char: '承', element: '金', meaning: '承继传统，承担责任', strokes: 8, gender: ['both'], pinyin: 'chéng' },
    { char: '春', element: '金', meaning: '春意盎然，生机勃勃', strokes: 9, gender: ['both'] },
    { char: '聪', element: '金', meaning: '聪明伶俐，智慧过人', strokes: 17, gender: ['both'], pinyin: 'cōng' },
    { char: '宸', element: '金', meaning: '帝王宫殿，尊贵高雅', strokes: 10, gender: ['both'], pinyin: 'chén' },
    { char: '晨', element: '金', meaning: '晨光熹微，朝气蓬勃', strokes: 11, gender: ['both'], pinyin: 'chén' },
    { char: '善', element: '金', meaning: '善良仁慈，心地善良', strokes: 12, gender: ['both'] },
    { char: '正', element: '金', meaning: '正直无私，堂堂正正', strokes: 5, gender: ['both'] },
    { char: '信', element: '金', meaning: '诚实守信，言而有信', strokes: 9, gender: ['both'], pinyin: 'xìn' },
    { char: '真', element: '金', meaning: '真诚善良，真心实意', strokes: 10, gender: ['both'] },
    { char: '思', element: '金', meaning: '思维敏捷，深思熟虑', strokes: 9, gender: ['both'], pinyin: 'sī' },
    { char: '钊', element: '金', meaning: '勉励激励，奋发向上', strokes: 10, gender: ['male'], pinyin: 'zhāo' },
    { char: '钦', element: '金', meaning: '钦佩敬重，德高望重', strokes: 12, gender: ['male'], pinyin: 'qīn' },
    { char: '铿', element: '金', meaning: '铿锵有力，声音洪亮', strokes: 15, gender: ['male'] },
    { char: '锋', element: '金', meaning: '锋芒毕露，才华出众', strokes: 15, gender: ['male'], pinyin: 'fēng' },
    { char: '钟', element: '金', meaning: '专一专注，钟情不渝', strokes: 17, gender: ['both'], pinyin: 'zhōng' },
    { char: '铁', element: '金', meaning: '坚强不屈，铁骨铮铮', strokes: 21, gender: ['male'] },
    { char: '镇', element: '金', meaning: '镇定自若，稳重大方', strokes: 18, gender: ['male'], pinyin: 'zhèn' },
    { char: '刚', element: '金', meaning: '刚强有力，刚正不阿', strokes: 10, gender: ['male'] },
    { char: '新', element: '金', meaning: '新颖独特，推陈出新', strokes: 13, gender: ['both'], pinyin: 'xīn' },
    { char: '心', element: '金', meaning: '善良纯真，用心良苦', strokes: 4, gender: ['both'], pinyin: 'xīn' },

    // ===== 木属性字符 =====
    { char: '林', element: '木', meaning: '茂林修竹，生机盎然', strokes: 8, gender: ['both'] },
    { char: '森', element: '木', meaning: '森森不息，蓬勃发展', strokes: 12, gender: ['male'] },
    { char: '楠', element: '木', meaning: '楠木珍贵，品质优良', strokes: 13, gender: ['both'], pinyin: 'nán' },
    { char: '柏', element: '木', meaning: '坚贞不渝，长青不老', strokes: 10, gender: ['male'], pinyin: 'bǎi' },
    { char: '桂', element: '木', meaning: '蟾宫折桂，功成名就', strokes: 10, gender: ['both'] },
    { char: '梓', element: '木', meaning: '梓材良木，成才之材', strokes: 11, gender: ['both'], pinyin: 'zǐ' },
    { char: '松', element: '木', meaning: '松柏长青，坚韧不拔', strokes: 8, gender: ['male'] },
    { char: '柯', element: '木', meaning: '法度准则，品行端正', strokes: 9, gender: ['male'] },
    { char: '杰', element: '木', meaning: '杰出人才，超群出众', strokes: 12, gender: ['male'], pinyin: 'jié' },
    { char: '梦', element: '木', meaning: '梦想成真，理想远大', strokes: 14, gender: ['both'], pinyin: 'mèng' },
    { char: '枫', element: '木', meaning: '枫叶如丹，美丽动人', strokes: 13, gender: ['both'] },
    { char: '桃', element: '木', meaning: '桃花运旺，美好姻缘', strokes: 10, gender: ['female'] },
    { char: '李', element: '木', meaning: '桃李满天下，德高望重', strokes: 7, gender: ['both'] },
    { char: '杨', element: '木', meaning: '杨柳依依，温柔多情', strokes: 13, gender: ['both'] },
    { char: '樱', element: '木', meaning: '樱花绚烂，美丽纯洁', strokes: 21, gender: ['female'] },
    { char: '义', element: '木', meaning: '义薄云天，正义凛然', strokes: 4, gender: ['male'] },
    { char: '艺', element: '木', meaning: '多才多艺，才华横溢', strokes: 4, gender: ['both'] },
    { char: '英', element: '木', meaning: '英雄豪杰，才华出众', strokes: 11, gender: ['both'], pinyin: 'yīng' },
    { char: '颖', element: '木', meaning: '聪颖过人，才思敏捷', strokes: 16, gender: ['female'], pinyin: 'yǐng' },
    { char: '毅', element: '木', meaning: '坚毅不屈，意志坚强', strokes: 15, gender: ['male'], pinyin: 'yì' },
    { char: '雅', element: '木', meaning: '高雅脱俗，品味不凡', strokes: 12, gender: ['female'], pinyin: 'yǎ' },
    { char: '彦', element: '木', meaning: '才德兼备，德才并茂', strokes: 9, gender: ['male'], pinyin: 'yàn' },
    { char: '言', element: '木', meaning: '言出必行，诚实可信', strokes: 7, gender: ['both'] },
    { char: '业', element: '木', meaning: '事业有成，业绩斐然', strokes: 13, gender: ['both'] },
    { char: '叶', element: '木', meaning: '叶茂根深，蓬勃发展', strokes: 15, gender: ['both'] },
    { char: '琪', element: '木', meaning: '美玉珍贵，琪花瑶草', strokes: 13, gender: ['female'], pinyin: 'qí' },
    { char: '琳', element: '木', meaning: '琳琅满目，美玉如琳', strokes: 13, gender: ['female'], pinyin: 'lín' },
    { char: '强', element: '木', meaning: '强大有力，坚强不屈', strokes: 12, gender: ['male'], pinyin: 'qiáng' },
    { char: '健', element: '木', meaning: '健康强壮，健步如飞', strokes: 11, gender: ['male'], pinyin: 'jiàn' },
    { char: '贤', element: '木', meaning: '贤良淑德，德才兼备', strokes: 15, gender: ['both'], pinyin: 'xián' },
    { char: '花', element: '木', meaning: '花开富贵，花好月圆', strokes: 8, gender: ['female'] },
    { char: '草', element: '木', meaning: '草木繁茂，生机盎然', strokes: 12, gender: ['both'] },
    { char: '树', element: '木', meaning: '树大根深，百年树人', strokes: 16, gender: ['both'] },
    { char: '竹', element: '木', meaning: '竹报平安，节节高升', strokes: 6, gender: ['both'] },
    { char: '荷', element: '木', meaning: '荷花出淤泥而不染', strokes: 13, gender: ['female'] },
    { char: '菊', element: '木', meaning: '菊花傲霜，品格高洁', strokes: 14, gender: ['female'] },
    { char: '梅', element: '木', meaning: '梅花香自苦寒来', strokes: 11, gender: ['female'] },
    { char: '兰', element: '木', meaning: '兰花幽香，品质高雅', strokes: 9, gender: ['female'], pinyin: 'lán' },
    { char: '萱', element: '木', meaning: '萱草忘忧，快乐无忧', strokes: 15, gender: ['female'], pinyin: 'xuān' },
    { char: '芝', element: '木', meaning: '灵芝仙草，珍贵难得', strokes: 10, gender: ['female'] },

    // ===== 水属性字符 =====
    { char: '海', element: '水', meaning: '海纳百川，胸襟广阔', strokes: 11, gender: ['male'], pinyin: 'hǎi' },
    { char: '涛', element: '水', meaning: '波涛壮阔，气势磅礴', strokes: 18, gender: ['male'], pinyin: 'tāo' },
    { char: '润', element: '水', meaning: '润泽万物，恩泽深厚', strokes: 16, gender: ['both'], pinyin: 'rùn' },
    { char: '泽', element: '水', meaning: '恩泽深厚，福泽绵长', strokes: 17, gender: ['both'], pinyin: 'zé' },
    { char: '涵', element: '水', meaning: '包容涵养，修养深厚', strokes: 12, gender: ['both'], pinyin: 'hán' },
    { char: '清', element: '水', meaning: '清正廉明，品格高洁', strokes: 12, gender: ['both'], pinyin: 'qīng' },
    { char: '浩', element: '水', meaning: '浩然正气，气势如虹', strokes: 11, gender: ['male'], pinyin: 'hào' },
    { char: '博', element: '水', meaning: '博学多才，博古通今', strokes: 12, gender: ['both'], pinyin: 'bó' },
    { char: '文', element: '水', meaning: '文质彬彬，文采飞扬', strokes: 4, gender: ['both'], pinyin: 'wén' },
    { char: '慧', element: '水', meaning: '聪慧过人，智慧如海', strokes: 15, gender: ['female'], pinyin: 'huì' },
    { char: '惠', element: '水', meaning: '惠泽他人，仁慈善良', strokes: 12, gender: ['female'], pinyin: 'huì' },
    { char: '美', element: '水', meaning: '美丽动人，美好如画', strokes: 9, gender: ['female'], pinyin: 'měi' },
    { char: '妍', element: '水', meaning: '妍丽动人，美好可爱', strokes: 7, gender: ['female'], pinyin: 'yán' },
    { char: '雨', element: '水', meaning: '甘露时雨，滋润万物', strokes: 8, gender: ['both'], pinyin: 'yǔ' },
    { char: '雪', element: '水', meaning: '雪花纯洁，冰清玉洁', strokes: 11, gender: ['female'], pinyin: 'xuě' },
    { char: '霖', element: '水', meaning: '甘霖普降，福泽深厚', strokes: 16, gender: ['both'], pinyin: 'lín' },
    { char: '江', element: '水', meaning: '江山如画，胸怀壮志', strokes: 7, gender: ['male'], pinyin: 'jiāng' },
    { char: '洋', element: '水', meaning: '洋洋大观，博大精深', strokes: 10, gender: ['male'], pinyin: 'yáng' },
    { char: '溪', element: '水', meaning: '溪水潺潺，清雅动人', strokes: 14, gender: ['both'], pinyin: 'xī' },
    { char: '湖', element: '水', meaning: '湖光山色，宁静致远', strokes: 13, gender: ['both'], pinyin: 'hú' },

    // ===== 火属性字符 =====
    { char: '炎', element: '火', meaning: '炎黄子孙，血脉相承', strokes: 8, gender: ['male'], pinyin: 'yán' },
    { char: '煜', element: '火', meaning: '光彩照人，熠熠生辉', strokes: 13, gender: ['both'], pinyin: 'yù' },
    { char: '烨', element: '火', meaning: '烨烨生辉，光芒万丈', strokes: 16, gender: ['both'], pinyin: 'yè' },
    { char: '灿', element: '火', meaning: '灿烂辉煌，光彩夺目', strokes: 17, gender: ['both'], pinyin: 'càn' },
    { char: '晖', element: '火', meaning: '阳光普照，温暖如春', strokes: 13, gender: ['both'], pinyin: 'huī' },
    { char: '明', element: '火', meaning: '明察秋毫，聪明睿智', strokes: 8, gender: ['both'], pinyin: 'míng' },
    { char: '德', element: '火', meaning: '德高望重，品德高尚', strokes: 15, gender: ['both'], pinyin: 'dé' },
    { char: '天', element: '火', meaning: '天高云淡，天赋异禀', strokes: 4, gender: ['both'], pinyin: 'tiān' },
    { char: '日', element: '火', meaning: '日新月异，光明正大', strokes: 4, gender: ['both'], pinyin: 'rì' },
    { char: '丹', element: '火', meaning: '丹心赤诚，纯真无邪', strokes: 4, gender: ['female'], pinyin: 'dān' },
    { char: '丽', element: '火', meaning: '美丽大方，丽质天成', strokes: 19, gender: ['female'], pinyin: 'lì' },
    { char: '娜', element: '火', meaning: '婀娜多姿，娜娜动人', strokes: 10, gender: ['female'], pinyin: 'nà' },
    { char: '婷', element: '火', meaning: '婷婷袅袅，美丽动人', strokes: 12, gender: ['female'], pinyin: 'tíng' },
    { char: '媛', element: '火', meaning: '淑女贤媛，品德优良', strokes: 12, gender: ['female'], pinyin: 'yuàn' },
    { char: '乐', element: '火', meaning: '快乐无忧，乐观向上', strokes: 15, gender: ['both'], pinyin: 'lè' },
    { char: '俊', element: '火', meaning: '俊朗英俊，人才俊秀', strokes: 9, gender: ['male'], pinyin: 'jùn' },
    { char: '亮', element: '火', meaning: '聪明亮丽，光明磊落', strokes: 9, gender: ['both'], pinyin: 'liàng' },
    { char: '晴', element: '火', meaning: '晴空万里，心情开朗', strokes: 12, gender: ['female'], pinyin: 'qíng' },
    { char: '朗', element: '火', meaning: '朗朗乾坤，开朗豁达', strokes: 11, gender: ['male'], pinyin: 'lǎng' },
    { char: '昊', element: '火', meaning: '昊天罔极，胸怀广阔', strokes: 8, gender: ['male'], pinyin: 'hào' },

    // ===== 土属性字符 =====
    { char: '宇', element: '土', meaning: '宇宙广阔，胸襟开阔', strokes: 6, gender: ['male'], pinyin: 'yǔ' },
    { char: '辰', element: '土', meaning: '星辰大海，志向远大', strokes: 7, gender: ['both'], pinyin: 'chén' },
    { char: '轩', element: '土', meaning: '气宇轩昂，风度翩翩', strokes: 10, gender: ['male'], pinyin: 'xuān' },
    { char: '坤', element: '土', meaning: '大地载物，厚德载物', strokes: 8, gender: ['male'], pinyin: 'kūn' },
    { char: '城', element: '土', meaning: '城池坚固，稳如磐石', strokes: 10, gender: ['both'], pinyin: 'chéng' },
    { char: '培', element: '土', meaning: '培育成才，栽培英才', strokes: 11, gender: ['both'], pinyin: 'péi' },
    { char: '均', element: '土', meaning: '均衡和谐，公平正义', strokes: 7, gender: ['both'], pinyin: 'jūn' },
    { char: '坚', element: '土', meaning: '坚强不屈，意志坚定', strokes: 11, gender: ['both'], pinyin: 'jiān' },
    { char: '安', element: '土', meaning: '安居乐业，平安幸福', strokes: 6, gender: ['both'], pinyin: 'ān' },
    { char: '远', element: '土', meaning: '远大前程，志向远大', strokes: 17, gender: ['both'], pinyin: 'yuǎn' },
    { char: '越', element: '土', meaning: '越来越好，超越自我', strokes: 12, gender: ['both'], pinyin: 'yuè' },
    { char: '优', element: '土', meaning: '优秀卓越，品学兼优', strokes: 17, gender: ['both'], pinyin: 'yōu' },
    { char: '阳', element: '土', meaning: '阳光灿烂，朝气蓬勃', strokes: 17, gender: ['both'], pinyin: 'yáng' },
    { char: '勇', element: '土', meaning: '勇敢无畏，英勇善战', strokes: 9, gender: ['male'], pinyin: 'yǒng' },
    { char: '威', element: '土', meaning: '威风凛凛，威武不屈', strokes: 9, gender: ['male'], pinyin: 'wēi' },
    { char: '峰', element: '土', meaning: '登峰造极，山峰险峻', strokes: 10, gender: ['male'], pinyin: 'fēng' },
    { char: '山', element: '土', meaning: '山高水长，稳重如山', strokes: 3, gender: ['both'], pinyin: 'shān' },
    { char: '岩', element: '土', meaning: '岩石坚固，坚定不移', strokes: 8, gender: ['male'], pinyin: 'yán' },
    { char: '墨', element: '土', meaning: '墨宝珍贵，文采飞扬', strokes: 15, gender: ['both'], pinyin: 'mò' },
    { char: '基', element: '土', meaning: '基础稳固，根基深厚', strokes: 11, gender: ['both'], pinyin: 'jī' },

    // ===== 通用美好字符 =====
    { char: '悦', element: '金', meaning: '心悦诚服，愉悦快乐', strokes: 11, gender: ['both'], pinyin: 'yuè' },
    { char: '喜', element: '金', meaning: '喜气洋洋，喜从天降', strokes: 12, gender: ['both'], pinyin: 'xǐ' },
    { char: '欢', element: '水', meaning: '欢声笑语，欢乐祥和', strokes: 22, gender: ['both'], pinyin: 'huān' },
    { char: '瑶', element: '火', meaning: '瑶池仙境，美玉如瑶', strokes: 15, gender: ['female'], pinyin: 'yáo' },
    { char: '诗', element: '金', meaning: '诗情画意，文采斐然', strokes: 13, gender: ['both'], pinyin: 'shī' },
    { char: '韵', element: '土', meaning: '韵味十足，风韵优雅', strokes: 19, gender: ['female'], pinyin: 'yùn' },
    { char: '雄', element: '水', meaning: '雄心壮志，英雄豪杰', strokes: 12, gender: ['male'], pinyin: 'xióng' },
    { char: '豪', element: '水', meaning: '豪情壮志，英雄豪杰', strokes: 14, gender: ['male'], pinyin: 'háo' },
    { char: '学', element: '水', meaning: '学而时习之，好学不倦', strokes: 16, gender: ['both'], pinyin: 'xué' },
    { char: '智', element: '火', meaning: '智慧超群，聪明智慧', strokes: 12, gender: ['both'], pinyin: 'zhì' }
];

// 由于篇幅限制，这里只包含了约80个精选字符
// 在实际应用中，可以根据需要继续扩展字库内容
// 包括更多五行属性的字、不同类别的字（如方位、季节、动物等）

// 导出字库数据
if (typeof module !== 'undefined' && module.exports) {
    module.exports = NAME_DATABASE;
} 